package main

import (
	"fmt"
	"strings"
)

// completionScript returns the completion script for shell: bash, zsh or
// fish. Each script covers xproxyctl (global flags, commands, their fixed
// words, flags and file arguments) and xproxy (its three flags).
func completionScript(shell string) (string, bool) {
	switch shell {
	case "bash":
		return bashCompletion(), true
	case "zsh":
		return zshCompletion(), true
	case "fish":
		return fishCompletion(), true
	}
	return "", false
}

func bashCompletion() string {
	var b strings.Builder
	b.WriteString("# bash completion for xproxyctl and xproxy (generated by xproxyctl completion bash)\n")
	b.WriteString("_xproxyctl() {\n")
	b.WriteString("    local cur prev words cword\n")
	b.WriteString("    if declare -F _init_completion >/dev/null 2>&1; then _init_completion || return; else\n")
	b.WriteString("        cur=${COMP_WORDS[COMP_CWORD]}; prev=${COMP_WORDS[COMP_CWORD-1]}; words=(\"${COMP_WORDS[@]}\"); cword=$COMP_CWORD; fi\n")
	fmt.Fprintf(&b, "    local commands=%q\n", strings.Join(commandNames(), " "))
	b.WriteString("    local i cmd=\n")
	b.WriteString("    for ((i = 1; i < cword; i++)); do\n")
	b.WriteString("        case ${words[i]} in\n")
	b.WriteString("            -socket|-config) ((i++)) ;;\n")
	b.WriteString("            -*) ;;\n")
	b.WriteString("            *) cmd=${words[i]}; break ;;\n")
	b.WriteString("        esac\n")
	b.WriteString("    done\n")
	b.WriteString("    if [[ -z $cmd ]]; then\n")
	b.WriteString("        case $prev in\n")
	b.WriteString("            -socket|-config) _xproxy_files; return ;;\n")
	b.WriteString("        esac\n")
	b.WriteString("        if [[ $cur == -* ]]; then COMPREPLY=($(compgen -W \"-socket -config -json\" -- \"$cur\")); return; fi\n")
	b.WriteString("        COMPREPLY=($(compgen -W \"$commands\" -- \"$cur\")); return\n")
	b.WriteString("    fi\n")
	b.WriteString("    case $cmd in\n")
	for _, c := range commandTable {
		words := append(append([]string{}, c.words...), c.flags...)
		if len(words) == 0 && !c.files {
			continue
		}
		fmt.Fprintf(&b, "        %s)", c.name)
		if len(words) > 0 {
			fmt.Fprintf(&b, " COMPREPLY=($(compgen -W %q -- \"$cur\"));", strings.Join(words, " "))
		}
		if c.files {
			b.WriteString(" _xproxy_files;")
		}
		b.WriteString(" ;;\n")
	}
	b.WriteString("    esac\n")
	b.WriteString("}\n")
	b.WriteString("_xproxy_files() {\n")
	b.WriteString("    if declare -F _filedir >/dev/null 2>&1; then _filedir; else COMPREPLY+=($(compgen -f -- \"$cur\")); fi\n")
	b.WriteString("}\n")
	b.WriteString("_xproxy() {\n")
	b.WriteString("    local cur=${COMP_WORDS[COMP_CWORD]} prev=${COMP_WORDS[COMP_CWORD-1]}\n")
	b.WriteString("    if [[ $prev == -config ]]; then _xproxy_files; return; fi\n")
	b.WriteString("    COMPREPLY=($(compgen -W \"-config -validate -version\" -- \"$cur\"))\n")
	b.WriteString("}\n")
	b.WriteString("complete -F _xproxyctl xproxyctl\n")
	b.WriteString("complete -F _xproxy xproxy\n")
	return b.String()
}

func zshCompletion() string {
	var b strings.Builder
	b.WriteString("#compdef xproxyctl xproxy\n")
	b.WriteString("# zsh completion for xproxyctl and xproxy (generated by xproxyctl completion zsh)\n\n")
	b.WriteString("_xproxyctl() {\n")
	b.WriteString("    local -a commands\n    commands=(\n")
	for _, c := range commandTable {
		fmt.Fprintf(&b, "        '%s:%s'\n", c.name, zshQuote(c.summary))
	}
	b.WriteString("    )\n")
	b.WriteString("    local curcontext=$curcontext state line\n    typeset -A opt_args\n")
	b.WriteString("    _arguments -C \\\n")
	b.WriteString("        '-socket[management socket]:socket:_files' \\\n")
	b.WriteString("        '-config[configuration file]:file:_files' \\\n")
	b.WriteString("        '-json[machine readable output]' \\\n")
	b.WriteString("        '1:command:->cmd' \\\n")
	b.WriteString("        '*::argument:->args'\n")
	b.WriteString("    case $state in\n")
	b.WriteString("        cmd) _describe -t commands 'xproxyctl command' commands ;;\n")
	b.WriteString("        args)\n            case $line[1] in\n")
	for _, c := range commandTable {
		words := append(append([]string{}, c.words...), c.flags...)
		if len(words) == 0 && !c.files {
			continue
		}
		fmt.Fprintf(&b, "                %s)", c.name)
		if len(words) > 0 {
			fmt.Fprintf(&b, " _values 'argument' %s;", strings.Join(words, " "))
		}
		if c.files {
			b.WriteString(" _files;")
		}
		b.WriteString(" ;;\n")
	}
	b.WriteString("            esac ;;\n    esac\n}\n\n")
	b.WriteString("_xproxy() {\n")
	b.WriteString("    _arguments \\\n")
	b.WriteString("        '-config[configuration file]:file:_files' \\\n")
	b.WriteString("        '-validate[validate the configuration and exit]' \\\n")
	b.WriteString("        '-version[print version and exit]'\n}\n\n")
	b.WriteString("case $service in\n    xproxy) _xproxy \"$@\" ;;\n    *) _xproxyctl \"$@\" ;;\nesac\n")
	return b.String()
}

func zshQuote(s string) string {
	s = strings.ReplaceAll(s, ":", `\:`)
	return strings.ReplaceAll(s, "'", `'\''`)
}

func fishCompletion() string {
	var b strings.Builder
	b.WriteString("# fish completion for xproxyctl and xproxy (generated by xproxyctl completion fish)\n")
	b.WriteString("complete -c xproxyctl -f\n")
	b.WriteString("complete -c xproxyctl -o socket -r -F -d 'management socket'\n")
	b.WriteString("complete -c xproxyctl -o config -r -F -d 'configuration file'\n")
	b.WriteString("complete -c xproxyctl -o json -d 'machine readable output'\n")
	names := strings.Join(commandNames(), " ")
	for _, c := range commandTable {
		fmt.Fprintf(&b, "complete -c xproxyctl -n 'not __fish_seen_subcommand_from %s' -a %s -d '%s'\n", names, c.name, fishQuote(c.summary))
	}
	for _, c := range commandTable {
		if len(c.words) > 0 {
			fmt.Fprintf(&b, "complete -c xproxyctl -n '__fish_seen_subcommand_from %s' -a '%s'\n", c.name, strings.Join(c.words, " "))
		}
		for _, f := range c.flags {
			fmt.Fprintf(&b, "complete -c xproxyctl -n '__fish_seen_subcommand_from %s' -o %s\n", c.name, strings.TrimPrefix(f, "-"))
		}
		if c.files {
			fmt.Fprintf(&b, "complete -c xproxyctl -n '__fish_seen_subcommand_from %s' -F\n", c.name)
		}
	}
	b.WriteString("complete -c xproxy -f\n")
	b.WriteString("complete -c xproxy -o config -r -F -d 'configuration file'\n")
	b.WriteString("complete -c xproxy -o validate -d 'validate the configuration and exit'\n")
	b.WriteString("complete -c xproxy -o version -d 'print version and exit'\n")
	return b.String()
}

func fishQuote(s string) string { return strings.ReplaceAll(s, "'", `\'`) }
