# Builds a static xproxy image from the source tree:
#   podman build -f deploy/kubernetes/Containerfile -t xproxy:1.2 .
FROM docker.io/library/golang:1.25 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags '-s -w -buildid=' -o /out/xproxy ./cmd/xproxy \
 && CGO_ENABLED=0 go build -trimpath -ldflags '-s -w -buildid=' -o /out/xproxyctl ./cmd/xproxyctl

FROM scratch
COPY --from=build /out/xproxy /out/xproxyctl /usr/bin/
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
USER 65532:65532
ENTRYPOINT ["/usr/bin/xproxy"]
CMD ["-config", "/etc/xproxy/xproxy.yaml"]
